export const products = [
  {
    id: "1",
    name: "Laptop",
    description: "Experience seamless productivity with this high-performance laptop, featuring a sleek design, powerful processor, and vibrant display. Perfect for work, gaming, or creative projects, it offers customizable storage and color options to suit your style.",
    price: 75000,
    stock: 10,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&h=500&fit=crop",
    rating: 4.5,
    created: "2024-05-01",
    attributes: [
      { name: "Color", values: ["Silver", "Black"] },
      { name: "Storage", values: ["256GB", "512GB"] },
    ],
    variations: [
      { sku: "LAP-SIL-256", attributes: { Color: "Silver", Storage: "256GB" }, stock: 3, price: 75000 },
      { sku: "LAP-SIL-512", attributes: { Color: "Silver", Storage: "512GB" }, stock: 2, price: 80000 },
      { sku: "LAP-BLK-256", attributes: { Color: "Black", Storage: "256GB" }, stock: 4, price: 75000 },
      { sku: "LAP-BLK-512", attributes: { Color: "Black", Storage: "512GB" }, stock: 1, price: 80000 },
    ],
  },
  {
    id: "2",
    name: "Smartphone",
    description: "Stay connected with this cutting-edge smartphone, boasting a stunning AMOLED display, advanced camera system, and lightning-fast performance. Available in multiple colors and storage capacities, it’s designed for modern lifestyles.",
    price: 45000,
    stock: 15,
    image: "https://images.pexels.com/photos/106400/pexels-photo-106400.jpeg?w=400&h=400&fit=crop",
    rating: 4.2,
    created: "2024-04-25",
    attributes: [
      { name: "Color", values: ["Blue", "White", "Black"] },
      { name: "Storage", values: ["128GB", "256GB"] },
    ],
    variations: [
      { sku: "SPH-BLU-128", attributes: { Color: "Blue", Storage: "128GB" }, stock: 4, price: 45000 },
      { sku: "SPH-BLU-256", attributes: { Color: "Blue", Storage: "256GB" }, stock: 3, price: 50000 },
      { sku: "SPH-WHT-128", attributes: { Color: "White", Storage: "128GB" }, stock: 2, price: 45000 },
      { sku: "SPH-WHT-256", attributes: { Color: "White", Storage: "256GB" }, stock: 1, price: 50000 },
      { sku: "SPH-BLK-128", attributes: { Color: "Black", Storage: "128GB" }, stock: 5, price: 45000 },
      { sku: "SPH-BLK-256", attributes: { Color: "Black", Storage: "256GB" }, stock: 0, price: 50000 },
    ],
  },
  {
    id: "3",
    name: "Wireless Earbuds",
    description: "Immerse yourself in crystal-clear audio with these wireless earbuds, featuring noise cancellation, long battery life, and a comfortable fit. Available in vibrant colors, they’re perfect for music lovers and on-the-go professionals.",
    price: 12000,
    stock: 10,
    image: "https://images.pexels.com/photos/3780680/pexels-photo-3780680.jpeg?w=400&h=400&fit=crop",
    rating: 4.0,
    created: "2024-06-10",
    attributes: [{ name: "Color", values: ["Black", "White", "Blue"] }],
    variations: [
      { sku: "EAR-BLK", attributes: { Color: "Black" }, stock: 5, price: 12000 },
      { sku: "EAR-WHT", attributes: { Color: "White" }, stock: 3, price: 12000 },
      { sku: "EAR-BLU", attributes: { Color: "Blue" }, stock: 2, price: 12000 },
    ],
  },
  {
    id: "4",
    name: "Smartwatch",
    description: "Track your fitness and stay connected with this stylish smartwatch, featuring heart rate monitoring, notifications, and a customizable band. Choose from sleek colors and durable materials for a perfect blend of fashion and function.",
    price: 20000,
    stock: 10,
    image: "https://images.pexels.com/photos/4379288/pexels-photo-4379288.jpeg?auto=compress&w=400&h=400&fit=crop",
    rating: 4.3,
    created: "2024-03-15",
    attributes: [
      { name: "Color", values: ["Black", "Silver"] },
      { name: "Band Material", values: ["Silicone", "Metal"] },
    ],
    variations: [
      { sku: "SWT-BLK-SIL", attributes: { Color: "Black", "Band Material": "Silicone" }, stock: 2, price: 20000 },
      { sku: "SWT-BLK-MET", attributes: { Color: "Black", "Band Material": "Metal" }, stock: 4, price: 22000 },
      { sku: "SWT-SIL-SIL", attributes: { Color: "Silver", "Band Material": "Silicone" }, stock: 1, price: 20000 },
      { sku: "SWT-SIL-MET", attributes: { Color: "Silver", "Band Material": "Metal" }, stock: 3, price: 22000 },
    ],
  },
  {
    id: "5",
    name: "Gaming Console",
    description: "Elevate your gaming experience with this powerful console, delivering stunning graphics, fast load times, and immersive gameplay. Available in multiple colors and storage options, it’s a must-have for gamers.",
    price: 35000,
    stock: 6,
    image: "https://images.pexels.com/photos/4523066/pexels-photo-4523066.jpeg?w=400&h=400&fit=crop",
    rating: 4.7,
    created: "2024-02-20",
    attributes: [
      { name: "Color", values: ["Black", "White"] },
      { name: "Storage", values: ["1TB", "2TB"] },
    ],
    variations: [
      { sku: "CON-BLK-1TB", attributes: { Color: "Black", Storage: "1TB" }, stock: 1, price: 35000 },
      { sku: "CON-BLK-2TB", attributes: { Color: "Black", Storage: "2TB" }, stock: 0, price: 40000 },
      { sku: "CON-WHT-1TB", attributes: { Color: "White", Storage: "1TB" }, stock: 3, price: 35000 },
      { sku: "CON-WHT-2TB", attributes: { Color: "White", Storage: "2TB" }, stock: 2, price: 40000 },
    ],
  },
  {
    id: "6",
    name: "Bluetooth Speaker",
    description: "Enjoy powerful sound anywhere with this portable Bluetooth speaker, featuring deep bass, long battery life, and a compact design. Available in bold colors, it’s ideal for parties or outdoor adventures.",
    price: 8000,
    stock: 9,
    image: "https://images.pexels.com/photos/14309813/pexels-photo-14309813.jpeg?w=400&h=400&fit=crop",
    rating: 4.1,
    created: "2024-05-20",
    attributes: [{ name: "Color", values: ["Black", "Red", "Blue"] }],
    variations: [
      { sku: "SPK-BLK", attributes: { Color: "Black" }, stock: 4, price: 8000 },
      { sku: "SPK-RED", attributes: { Color: "Red" }, stock: 2, price: 8000 },
      { sku: "SPK-BLU", attributes: { Color: "Blue" }, stock: 3, price: 8000 },
    ],
  },
  {
    id: "7",
    name: "Tablet",
    description: "Unleash your creativity with this versatile tablet, featuring a high-resolution display, powerful performance, and long battery life. Perfect for work or entertainment, it comes in sleek colors and storage options.",
    price: 30000,
    stock: 10,
    image: "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?w=400&h=400&fit=crop",
    rating: 4.4,
    created: "2024-01-10",
    attributes: [
      { name: "Color", values: ["Space Gray", "Silver"] },
      { name: "Storage", values: ["64GB", "128GB"] },
    ],
    variations: [
      { sku: "TAB-GRY-64", attributes: { Color: "Space Gray", Storage: "64GB" }, stock: 3, price: 30000 },
      { sku: "TAB-GRY-128", attributes: { Color: "Space Gray", Storage: "128GB" }, stock: 1, price: 35000 },
      { sku: "TAB-SIL-64", attributes: { Color: "Silver", Storage: "64GB" }, stock: 4, price: 30000 },
      { sku: "TAB-SIL-128", attributes: { Color: "Silver", Storage: "128GB" }, stock: 2, price: 35000 },
    ],
  },
  {
    id: "8",
    name: "Digital Camera",
    description: "Capture life’s moments with this professional-grade digital camera, featuring high-resolution imaging, fast autofocus, and versatile lens options. Available in sleek colors, it’s perfect for photographers of all levels.",
    price: 60000,
    stock: 6,
    image: "https://images.pexels.com/photos/279906/pexels-photo-279906.jpeg?auto=compress&w=400&h=400&fit=crop",
    rating: 4.6,
    created: "2024-04-01",
    attributes: [
      { name: "Color", values: ["Black", "Silver"] },
      { name: "Lens Type", values: ["Standard", "Zoom"] },
    ],
    variations: [
      { sku: "CAM-BLK-STD", attributes: { Color: "Black", "Lens Type": "Standard" }, stock: 2, price: 60000 },
      { sku: "CAM-BLK-ZOOM", attributes: { Color: "Black", "Lens Type": "Zoom" }, stock: 3, price: 65000 },
      { sku: "CAM-SIL-STD", attributes: { Color: "Silver", "Lens Type": "Standard" }, stock: 1, price: 60000 },
      { sku: "CAM-SIL-ZOOM", attributes: { Color: "Silver", "Lens Type": "Zoom" }, stock: 0, price: 65000 },
    ],
  },
  {
    id: "9",
    name: "Headphones",
    description: "Enjoy superior sound quality with these comfortable headphones, featuring noise isolation and a durable design. Available in over-ear or on-ear styles and sleek colors, they’re perfect for music and calls.",
    price: 15000,
    stock: 2,
    attributes: [],
    variations: [],
    image: "https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?w=400&h=400&fit=crop",
    rating: 4.2,
    created: "2024-03-01",
  },
  {
    id: "10",
    name: "Portable Charger",
    description: "Keep your devices powered on the go with this compact portable charger, offering fast charging and high capacity. Available in multiple colors and capacities, it’s a reliable companion for travel or daily use.",
    price: 5000,
    stock: 0,
    image: "https://images.pexels.com/photos/3921704/pexels-photo-3921704.jpeg?auto=compress&w=400&h=400&fit=crop",
    rating: 4.0,
    created: "2024-06-01",
    attributes: [
      { name: "Color", values: ["Black", "White"] },
      { name: "Capacity", values: ["10000mAh", "20000mAh"] },
    ],
    variations: [
      { sku: "PCH-BLK-10K", attributes: { Color: "Black", Capacity: "10000mAh" }, stock: 0, price: 5000 },
      { sku: "PCH-BLK-20K", attributes: { Color: "White", Capacity: "20000mAh" }, stock: 0, price: 7000 },
    ],
  },
];